language: ruby
env:
  global:
    - GIT_COMMITTER_NAME: "r7kamura"
    - GIT_COMMITTER_EMAIL: "r7kamura@gmail.com"
    - GIT_AUTHOR_NAME: "r7kamura"
    - GIT_AUTHOR_EMAIL: "r7kamura@gmail.com"
    - secure: "caVcOKNB8nhLbR25WFpzm9nOvWOPuLc+VF8OsdPrSrMEVvK5k2t4d/RGSzVzOnr54kQNJs5ttcaKVXwkyl1dnKrxzwxE7Z3QEF4XjqaOMuJeJ6qatNe4hco9w2DEqPzIfOzt/zjwPa58ZYfAgolP9kF5m5iwN/jaNYRjKt40dUI="
script:
    - bundle exec middleman build
after_success:
    - cd build
    - git init
    - git add --all
    - git commit -m "Update from Travis CI"
    - 'git push --quiet https://$GITHUB_TOKEN@github.com/r7kamura/r7kamura.github.io.git master -f 2> /dev/null'
